services:
  - type: web
    name: xai-community-backend
    runtime: python
    rootDir: ./backend
    buildCommand: |
      pip install uv
      uv sync --frozen
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    
  # 선택사항: 정적 자산 서비스 (필요시)
  # - type: static
  #   name: xai-community-static
  #   staticPublishPath: ./backend/uploads
  #   buildCommand: echo "No build needed for static files"